name: Pipeline - Development
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  development:
    if: github.ref == 'refs/heads/development' || github.event.pull_request.base.ref == 'development'
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: curamet
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Run Linting
        run: npm run lint
      
      - name: Run Tests
        run: npm test
        env:
          DB_HOST: localhost
          DB_USER: root
          DB_PASSWORD: password
          DB_DATABASE: curamet
      
      - name: Build
        run: npm run build
